clf reset
set(gcf,'defaultuicontrolunits','normalized');
set(gcf,'defaultuicontrolfontsize',18);
set(gcf,'defaultuicontrolhorizontal','left');

H=axes( 'unit' , 'normalized' , 'position' ,[0,0,1,1], 'visible' , 'off' );
set(gcf, 'currentaxes' ,H);
h_fig=get(H, 'parent' );
set(h_fig, 'unit' , 'normalized' , 'position' ,[0.1,0.2,0.8,0.8],'Toolbar','figure');

h_text=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.66,0.79,0.05,0.05], ...
'horizontal' , 'left' , 'string' , 'x-axis range' );

h_edit0=uicontrol(h_fig, 'style' , 'edit' , ...
'unit' , 'normalized' , 'position' ,[0.73,0.79,0.10,0.05], ...
'horizontal' , 'left' , ...
'callback' ,[ ...
'x0=str2num(get(gcbo,''string''));' ]);

h_edit1=uicontrol(h_fig, 'style' , 'edit' , ...
'unit' , 'normalized' , 'position' ,[0.85,0.79,0.10,0.05], ...
'horizontal' , 'left' , ...
'callback' ,[ ...
'x1=str2num(get(gcbo,''string''));' ]);

h_text1=uicontrol(h_fig, 'style' , 'text' , ...
'unit' , 'normalized' , 'position' ,[0.66,0.73,0.05,0.05], ...
'horizontal' , 'left' , 'string' , 'y-axis range' );

h_edit2=uicontrol(h_fig, 'style' , 'edit' , ...
'unit' , 'normalized' , 'position' ,[0.73,0.73,0.10,0.05], ...
'horizontal' , 'left' , ...
'callback' ,[ ...
'y0=str2num(get(gcbo,''string''));' ]);

h_edit3=uicontrol(h_fig, 'style' , 'edit' , ...
'unit' , 'normalized' , 'position' ,[0.85,0.73,0.10,0.05], ...
'horizontal' , 'left' , ...
'callback' ,[ ...
'y1=str2num(get(gcbo,''string''));' ]);



h_axes=axes( 'parent' ,h_fig, ...
'unit' , 'normalized' , 'position' ,[0.1,0.15,0.55,0.7]);
%[filename, pathname] = uigetfile({'*.txt';'*.*'},'File Selector');
tempdir = uigetdir(pwd, 'Select a folder');
cd(tempdir);
filelist = dir(fullfile(tempdir, '*.txt'));
[wavelength,intensity,spectime]=readLWCC(filelist(1).name);plot(wavelength,intensity);title([spectime filelist(1).name]);
xlabel('wavelength(nm)'); ylabel ('absorbance');
%warndlg('please set x y range!');
i=2;
h_push0=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.66,0.57,0.15,0.14], ...
'string' , 'next one' ,'callback' ,['i=i+1;' '[wavelength,intensity,spectime]=readLWCC(filelist(i).name);'...
'plot(wavelength,intensity);title([spectime filelist(i).name]);xlim([x0 x1]);ylim([y0 y1]);'...
'xlabel(''wavelength(nm)''); ylabel (''absorbance'');']);


h_push3=uicontrol(h_fig, 'style' , 'push' , ...
'unit' , 'normalized' , 'position' ,[0.82,0.57,0.15,0.14], ...
'string' , 'last one' ,'callback' ,['i=i-1;' '[wavelength,intensity,spectime]=readLWCC(filelist(i).name);'...
'plot(wavelength,intensity);title([spectime filelist(i).name]);xlim([x0 x1]);ylim([y0 y1]);'...
'xlabel(''wavelength(nm)''); ylabel (''absorbance'');']);



