%add isoprene,propane, propene
%keep in mind, no any comments inside the brackets of set, otherwise it
%will screw up.
%dont ever use 'legend' with this program, otherwise it will slow down the
%program significantly, which is found out by profiler.
figure
clf reset
i=1;
set(gcf,'unit','normalized','position',[0.01,0.03,0.95,0.9]);
set(gcf,'defaultuicontrolunits','normalized');
set(gcf,'defaultuicontrolfontsize',11);
set(gcf,'defaultuicontrolhorizontal','left');
set(gcf,'menubar','none');

str='OHR';
set(gcf,'name',str,'numbertitle','off');

showOHR_arctas;
%z1a:1 is first line, a is the first cell.
zleft=0.52;
zbottom=0.87;
zwidth=0.12;
zheight=0.1;
zhordist=0.08;
zvertdist=0.05;

z1a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom,zwidth,zheight],...
    'String','decay no.');
z1b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom,zwidth,zheight],...
    'string',num2str(i));
z1c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom,zwidth,zheight],...
    'String','C3F6On');
z1d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom,zwidth,zheight],...
    'String',num2str(c3f6Meanswitch(i)));
z1e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom,zwidth,zheight],...
    'String','CalBit');
z1f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom,zwidth,zheight],...
    'string',num2str(nanmean(calFlag(i,:))));

z2a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*1,zwidth,zheight],...
    'String','NoOtlirs(blk)');
z2b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*1,zwidth,zheight],...
    'string',num2str(noOutLierDecay(i)));
z2c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*1,zwidth,zheight],...
    'String','Rsquare:');
z2d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*1,zwidth,zheight],...
    'String',num2str(noOutLierR2(i)));
z2e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*1,zwidth,zheight],...
    'String','Intercept');
z2f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*1,zwidth,zheight],...
    'string',num2str(noOutLierIntercept(i)));

% z3a=uicontrol(gcf,'style','text',...
%     'position',[zleft,zbottom-zvertdist*2,zwidth,zheight],...
%     'String','f0NoOtlirs');
% z3b=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*1,zbottom-zvertdist*2,zwidth,zheight],...
%     'string',num2str(f0NoOutLierDecay(i)));
% z3c=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*2,zbottom-zvertdist*2,zwidth,zheight],...
%     'String','Rsquare:');
% z3d=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*3,zbottom-zvertdist*2,zwidth,zheight],...
%     'String',num2str(f0NoOutLierR2(i)));
% z3e=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*4,zbottom-zvertdist*2,zwidth,zheight],...
%     'String','Intercept');
% z3f=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*5,zbottom-zvertdist*2,zwidth,zheight],...
%     'string',num2str(f0NoOutLierIntercept(i)));

z4a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*3,zwidth,zheight],...
    'String','Robust(red)');
z4b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*3,zwidth,zheight],...
    'string',num2str(robDecay(i)));
z4c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*3,zwidth,zheight],...
    'String','Rsquare');
z4d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*3,zwidth,zheight],...
    'String',num2str(robR2(i)));
z4e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*3,zwidth,zheight],...
    'String','intercept:');
z4f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*3,zwidth,zheight],...
    'string',num2str(robIntercept(i)));

% z5a=uicontrol(gcf,'style','text',...
%     'position',[zleft,zbottom-zvertdist*4,zwidth,zheight],...
%     'String','f0Robust');
% z5b=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*1,zbottom-zvertdist*4,zwidth,zheight],...
%     'string',num2str(f0RobDecay(i)));
% z5c=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*2,zbottom-zvertdist*4,zwidth,zheight],...
%     'String','Rsquare:');
% z5d=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*3,zbottom-zvertdist*4,zwidth,zheight],...
%     'String',num2str(f0RobR2(i)));
% z5e=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*4,zbottom-zvertdist*4,zwidth,zheight],...
%     'String','intercept:');
% z5f=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*5,zbottom-zvertdist*4,zwidth,zheight],...
%     'string',num2str(f0RobIntercept(i)));

z6a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*5,zwidth,zheight],...
    'String','Max (green)');
z6b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*5,zwidth,zheight],...
    'string',num2str(maxDecay(i)));
z6c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*5,zwidth,zheight],...
    'String','Rsquare');
z6d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*5,zwidth,zheight],...
    'String',num2str(maxR2(i)));
z6e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*5,zwidth,zheight],...
    'String','Intercept');
z6f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*5,zwidth,zheight],...
    'string',num2str(maxIntercept(i)));

% z7a=uicontrol(gcf,'style','text',...
%     'position',[zleft,zbottom-zvertdist*6,zwidth,zheight],...
%     'String','f0Max');
% z7b=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*1,zbottom-zvertdist*6,zwidth,zheight],...
%     'string',num2str(f0MaxDecay(i)));
% z7c=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*2,zbottom-zvertdist*6,zwidth,zheight],...
%     'String','Rsquare');
% z7d=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*3,zbottom-zvertdist*6,zwidth,zheight],...
%     'String',num2str(f0MaxR2(i)));
% z7e=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*4,zbottom-zvertdist*6,zwidth,zheight],...
%     'String','Intercept');
% z7f=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*5,zbottom-zvertdist*6,zwidth,zheight],...
%     'string',num2str(f0MaxIntercept(i)));

% z8a=uicontrol(gcf,'style','text',...
%     'position',[zleft,zbottom-zvertdist*7,zwidth,zheight],...
%     'String','CorrNoOtlir');
% z8b=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*1,zbottom-zvertdist*7,zwidth,zheight],...
%     'string',num2str(corrNoOutLierDecay(i)));
% z8c=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*2,zbottom-zvertdist*7,zwidth,zheight],...
%     'String','Rsquare');
% z8d=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*3,zbottom-zvertdist*7,zwidth,zheight],...
%     'String',num2str(corrNoOutLierR2(i)));
% z8e=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*4,zbottom-zvertdist*7,zwidth,zheight],...
%     'String','Intercept');
% z8f=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*5,zbottom-zvertdist*7,zwidth,zheight],...
%     'string',num2str(corrNoOutLierIntercept(i)));

% z9a=uicontrol(gcf,'style','text',...
%     'position',[zleft,zbottom-zvertdist*8,zwidth,zheight],...
%     'String','CorrRobust');
% z9b=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*1,zbottom-zvertdist*8,zwidth,zheight],...
%     'string',num2str(corrRobDecay(i)));
% z9c=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*2,zbottom-zvertdist*8,zwidth,zheight],...
%     'String','Rsquare');
% z9d=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*3,zbottom-zvertdist*8,zwidth,zheight],...
%     'String',num2str(corrRobR2(i)));
% z9e=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*4,zbottom-zvertdist*8,zwidth,zheight],...
%     'String','Intercept');
% z9f=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*5,zbottom-zvertdist*8,zwidth,zheight],...
%     'string',num2str(corrRobIntercept(i)));
% 
z10a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*9,zwidth,zheight],...
    'String','Start@');
z10b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*9,zwidth,zheight],...
    'string',datestr(startPointTime(i)/24/3600,13));
z10c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*9,zwidth,zheight],...
    'String','T1');
z10d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*9,zwidth,zheight],...
    'String',[num2str(nanmean(temp1On(i,:))) ' C']);
z10e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*9,zwidth,zheight],...
    'String','T2');
z10f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*9,zwidth,zheight],...
    'string',[num2str(nanmean(temp2On(i,:))) ' C']);

z11a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*10,zwidth,zheight],...
    'String','TubePress');
z11b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*10,zwidth,zheight],...
    'string',[num2str(meanTubePress(i)) ' kPa']);
z11c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*10,zwidth,zheight],...
    'String','Blower:');
z11d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*10,zwidth,zheight],...
    'String',[num2str(mean(blower(i,:))) ' volts']);
z11e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*10,zwidth,zheight],...
    'String','CorrVel');
z11f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*10,zwidth,zheight],...
    'string',[num2str(mean(airVelocity(i,(stepNumber-1):stepNumber))) ' m/s']);

z12a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*11,zwidth,zheight],...
    'String','startP');
z12b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*11,zwidth,zheight],...
    'string',[num2str(tubeStartPress(i)) ' kPa']);
z12c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*11,zwidth,zheight],...
    'String','H2OFlo');
z12d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*11,zwidth,zheight],...
    'String',[num2str(mean(waterVaporFlow(i,:))) ' L/min']);
z12e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*11,zwidth,zheight],...
    'String','OrigVel');
z12f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*11,zwidth,zheight],...
    'string',[num2str(mean(airVelReading(i,(stepNumber-1):stepNumber))) ' m/s']);
z13a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*12,zwidth,zheight],...
    'String','endP');
z13b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*12,zwidth,zheight],...
    'string',[num2str(tubeEndPress(i)) ' kPa']);
z13c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*12,zwidth,zheight],...
    'String','MassFlo');
z13d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*12,zwidth,zheight],...
    'string',[num2str(mean(massFlow(i,(stepNumber-1):stepNumber))) ' L/min']);
z13e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*12,zwidth,zheight],...
    'String','Reynolds');
z13f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*12,zwidth,zheight],...
    'string',num2str(reynoldsNumber(i)) );
% z14a=uicontrol(gcf,'style','text',...
%     'position',[zleft,zbottom-zvertdist*13,zwidth,zheight],...
%     'String','Amb NO');
% z14b=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*1,zbottom-zvertdist*13,zwidth,zheight],...
%     'string',[num2str(mean(noConc(i,:))) ' ppb']);
z14a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*13,zwidth,zheight],...
    'String','cellP');
z14b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*13,zwidth,zheight],...
    'string',[num2str(mean(cellPress(i,:))) ' mbar']);
z14c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*13,zwidth,zheight],...
    'String','add Flow');
z14d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*13,zwidth,zheight],...
    'String',[num2str(nanmean(coAddFlow(i,:))) ' sccm']);
z14e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*13,zwidth,zheight],...
    'String','cal CO');
z14f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*13,zwidth,zheight],...
    'string',[num2str(calCO(i)) ' s-1']);

z15a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*14,zwidth,zheight],...
    'String','cal c3f6:');
z15b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*14,zwidth,zheight],...
    'string',[num2str(calC3F6(i)) ' s-1']);
z15c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*14,zwidth,zheight],...
    'String','C3F6Mole');
z15d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*14,zwidth,zheight],...
    'String',[num2str(c3f6Mole(i),'%7.2e') '#/cm3']);
% z15e=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*4,zbottom-zvertdist*14,zwidth,zheight],...
%     'String','Propene');
% z15f=uicontrol(gcf,'style','text',...
%     'position',[zleft+zhordist*5,zbottom-zvertdist*14,zwidth,zheight],...
%     'string',[num2str(mean(calPropene(i))) ' s-1']);

z16a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*15,zwidth,zheight],...
    'String','c3f6Press');
z16b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*15,zwidth,zheight],...
    'string',[num2str(nanmean(c3f6Press(i,:))) ' kpa']);
z16c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*15,zwidth,zheight],...
    'String','C3F6flow');
z16d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*15,zwidth,zheight],...
    'String',[num2str(nanmean(c3f6Addflow(i,:))) ' sccm']);

z17a=uicontrol(gcf,'style','text',...
    'position',[zleft,zbottom-zvertdist*16,zwidth,zheight],...
    'String','calIsop');
z17b=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*1,zbottom-zvertdist*16,zwidth,zheight],...
    'string',[num2str(calIsoprene(i)) ' s-1']);
z17c=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*2,zbottom-zvertdist*16,zwidth,zheight],...
    'String','calPropane');
z17d=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*3,zbottom-zvertdist*16,zwidth,zheight],...
    'String',[num2str(calPropane(i)) ' s-1']);
z17e=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*4,zbottom-zvertdist*16,zwidth,zheight],...
    'String','calPropene');
z17f=uicontrol(gcf,'style','text',...
    'position',[zleft+zhordist*5,zbottom-zvertdist*16,zwidth,zheight],...
    'String',[num2str(calPropene(i)) ' s-1']);

zpush1=uicontrol(gcf,'Style','push',...
    'position',[0.75,0.05,0.08,0.08],'string','Next');
% while i>0&i<=length(oh_Decay)
set(zpush1,'callback',['i=i+1;'...
    'showOHR2_arctas;',...
    ]);
zpush2=uicontrol(gcf,'Style','push',...
    'position',[0.65,0.05,0.08,0.08],'string','Prev');
set(zpush2,'callback',['i=i-1;',...
    'showOHR2_arctas;',...
    ]);
zpush3=uicontrol(gcf,'Style','push',...
    'position',[0.5,0.05,0.08,0.08],'string','Prev hour');
set(zpush3,'callback',['i=i-15;',...
    'showOHR2_arctas;',...
    ]);
zpush4=uicontrol(gcf,'Style','push',...
    'position',[0.9,0.05,0.08,0.08],'string','Next hour');
set(zpush4,'callback',['i=i+15;',...
    'showOHR2_arctas;',...
    ]);
