    set(z1b,'string',num2str(i));...
    set(z1d,'string',num2str(c3f6Meanswitch(i)));...
    set(z1f,'string',num2str(nanmean(calFlag(i,:))));...    
    set(z2b,'string',num2str(noOutLierDecay(i)));...
    set(z2d,'string',num2str(noOutLierR2(i)));...
    set(z2f,'string',num2str(noOutLierIntercept(i)));...
%     set(z3b,'string',num2str(f0NoOutLierDecay(i)));...
%     set(z3d,'string',num2str(f0NoOutLierR2(i)));...
%     set(z3f,'string',num2str(f0NoOutLierIntercept(i)));...
    set(z4b,'string',num2str(robDecay(i)));...
    set(z4d,'string',num2str(robR2(i)));...
    set(z4f,'string',num2str(robIntercept(i)));...
%     set(z5b,'string',num2str(f0RobDecay(i)));...
%     set(z5d,'string',num2str(f0RobR2(i)));...
%     set(z5f,'string',num2str(f0RobIntercept(i)));...
    set(z6b,'string',num2str(maxDecay(i)));...
    set(z6d,'string',num2str(maxR2(i)));...
    set(z6f,'string',num2str(maxIntercept(i)));...    
%     set(z7b,'string',num2str(f0MaxDecay(i)));...
%     set(z7d,'string',num2str(f0MaxR2(i)));...
%     set(z7f,'string',num2str(f0MaxIntercept(i)));...
%     set(z8b,'string',num2str(corrNoOutLierDecay(i)));...
%     set(z8d,'string',num2str(corrNoOutLierR2(i)));...
%     set(z8f,'string',num2str(corrNoOutLierIntercept(i)));...
%     set(z9b,'string',num2str(corrRobDecay(i)));...
%     set(z9d,'string',num2str(corrRobR2(i)));...
%     set(z9f,'string',num2str(corrRobIntercept(i)));...
    set(z10b,'string',datestr(startPointTime(i)/24/3600,13));...
    set(z10d,'string',[num2str(nanmean(temp1On(i,:))) ' C']);...
    set(z10f,'string',[num2str(nanmean(temp2On(i,:))) ' C']);...
    set(z11b,'string',[num2str(meanTubePress(i)) ' kPa']);...
    set(z11d,'string',[num2str(mean(blower(i,:))) ' volts']);...
    set(z11f,'string',[num2str(meanVelocity(i)) ' m/s']);...    
    set(z12b,'string',[num2str(tubeStartPress(i)) ' kPa']);...
    set(z12d,'string',[num2str(mean(waterVaporFlow(i,:))) ' L/min']);...
    set(z12f,'string',[num2str(mean(airVelReading(i,(stepNumber-1):stepNumber))) ' m/s']);...
    set(z13b,'string',[num2str(tubeEndPress(i)) ' kPa']);...
    set(z13d,'string',[num2str(mean(massFlow(i,(stepNumber-1):stepNumber))) ' L/min']);...
    set(z13f,'string',num2str(reynoldsNumber(i)));...
    set(z14b,'string',[num2str(mean(cellPress(i,:))) ' mbar']);...
    set(z14d,'string',[num2str(nanmean(coAddFlow(i,:))) ' sccm']);...
    set(z14f,'string',[num2str(mean(calCO(i))) ' s-1']);...
    set(z15b,'string',[num2str(calC3F6(i)) ' s-1']);...
    set(z15d,'string',[num2str(c3f6Mole(i),'%7.2e') '#/cm3']);...
%     set(z15f,'string',[num2str(mean(calPropene(i))) ' s-1']);...
    set(z16b,'string',[num2str(nanmean(c3f6Press(i,:))) ' kpa']);...
    set(z16d,'string',[num2str(nanmean(c3f6Addflow(i,:))) ' sccm']);...
    set(z17b,'string',[num2str(calIsoprene(i)) ' s-1']);...
    set(z17d,'string',[num2str(calPropane(i)) ' s-1']);...
    set(z17f,'string',[num2str(calPropene(i)) ' s-1']);...
   

subplot('position',[0.04,0.52,0.45,0.45])
plot(timeDecay(i,:),ohExpDecay(i,:),'b.','markersize',16);
% legend('F1','Corrected','F0',3);
hold;
plot(timeDecay(i,:),timeDecay(i,:).*noOutLierDecay(i)+noOutLierIntercept(i),'k-',...
    timeDecay(i,:),timeDecay(i,:).*robDecay(i)+robIntercept(i),'r-',...
    timeDecay(i,:),timeDecay(i,:).*maxDecay(i)+maxIntercept(i),'g-');
% ylim([0 7]);
% plot(timeDecay(i,:),timeDecay(i,:).*f0NoOutLierDecay(i)+f0NoOutLierIntercept(i),'k-');
% legend('data','Decay without outliers','Robust Regression','maxdecay',3);
Grid on;
ylabel('Signal');
hold;
subplot('position',[0.04,0.04,0.45,0.45])
plot(timeDecay(i,:),airVelocity(i,:),'r.');
Grid on;
ylabel('Air Velocity');
